<a href="https://colab.research.google.com/github/pathak-gaurav/machine_learning_course/blob/master/Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('home_age_prices.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [0]:
import math
median_bedroom = math.floor(df.bedroom.median())

In [0]:
df.bedroom = df.bedroom.fillna(median_bedroom)

In [0]:
regression = linear_model.LinearRegression()

In [12]:
regression.fit(df[['area','bedroom','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
regression.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [14]:
regression.intercept_

383724.99999999994

In [15]:
regression.predict([[3000,3,40]])

array([444400.])

In [18]:
#y = m1*area + m2* bedroom + m3*age + b
137.25*3000 + (-26025 * 3) + (-6825 * 40) + 383724.99999999994

444399.99999999994

In [19]:
regression.predict([[2500,4,5]])

array([588625.])

In [0]:
hiring_df = pd.read_csv('hiring.csv')

In [22]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [0]:
import math
test_score_median = math.floor(hiring_df['test_score(out of 10)'].median())

In [0]:
hiring_df['test_score(out of 10)'] = hiring_df['test_score(out of 10)'].fillna(test_score_median)

In [30]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [34]:
!pip install -q word2number

In [0]:
from word2number import w2n

In [0]:
hiring_df['experience'] = hiring_df['experience'].fillna('zero')

In [43]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [0]:
hiring_df['experience'] = hiring_df['experience'].apply(w2n.word_to_num)

In [52]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [54]:
regression_hiring = linear_model.LinearRegression()
regression_hiring.fit(hiring_df[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring_df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [55]:
regression_hiring.predict([[2,9,6]])

array([53205.96797671])

In [56]:
regression_hiring.predict([[12,10,10]])

array([92002.18340611])